export interface GalleryImage {
  src: string;
  alt: string;
}

export interface Service {
  slug: string;
  title: string;
  shortDescription: string;
  longDescription: string;
  image: string;
  heroImage: string;
  features: string[];
  faq: { question: string; answer: string }[];
  gallery?: GalleryImage[];
}

export const services: Service[] = [
  {
    slug: "channel-letters",
    title: "Channel Letters",
    shortDescription: "Vibrant, individual LED-illuminated letters that offer maximum visibility night and day.",
    longDescription: "Channel letters are three-dimensional, individually fabricated letters commonly used for building signage. Each letter contains LED modules that illuminate the face, creating a bold, professional look that draws attention 24/7. They are the go-to choice for retail stores, restaurants, corporate offices, and franchises looking for high-impact exterior signage. At Signarama Vaughan, we fabricate channel letters in-house using premium aluminum and acrylic, with energy-efficient LEDs rated for 50,000+ hours of operation.",
    image: "/images/services/channel-letters.jpg",
    heroImage: "/images/heroes/channel-letters-night.jpg",
    features: ["Front-lit (face illuminated)", "Reverse-lit / Halo-lit (backglow effect)", "Open-face (exposed neon or LED)", "Combination front and back lit", "Custom colors and finishes", "Energy-efficient LED modules"],
    faq: [
      { question: "How much do channel letters cost?", answer: "Channel letter pricing depends on size, quantity, illumination type, and installation complexity. A typical storefront set ranges from $3,000 to $15,000+. Contact us for a free quote specific to your project." },
      { question: "Do channel letters require a permit in Vaughan?", answer: "Yes, most exterior signage in Vaughan requires a sign permit from the City. We handle the permit application process for you as part of our full-service offering." },
      { question: "How long do LED channel letters last?", answer: "Our LED modules are rated for 50,000+ hours of operation — that is over 11 years of continuous use. LEDs also consume 50-80% less energy than traditional neon." },
      { question: "How long does it take to get channel letters installed?", answer: "From design approval to installation, a typical channel letter project takes 3-5 weeks. Rush orders may be available depending on complexity." },
    ],
    gallery: [
      { src: "/images/gallery/channel-letters/channel-pullman-2.jpg", alt: "Pullman Hotel channel letters" },
      { src: "/images/gallery/channel-letters/channel-walking-on-a-cloud.jpg", alt: "Walking On A Cloud illuminated channel letters" },
      { src: "/images/gallery/channel-letters/channel-freshii.jpg", alt: "Freshii restaurant channel letters" },
      { src: "/images/gallery/channel-letters/channel-ethan-allen.jpg", alt: "Ethan Allen storefront channel letters" },
      { src: "/images/gallery/channel-letters/channel-allmart.jpg", alt: "Allmart channel letters" },
      { src: "/images/gallery/channel-letters/channel-canaroma.jpg", alt: "Canaroma channel letters" },
      { src: "/images/gallery/channel-letters/channel-makers.jpg", alt: "Makers channel letter sign" },
      { src: "/images/gallery/channel-letters/channel-mazzzing.jpg", alt: "Mazzzing channel letters" },
      { src: "/images/gallery/channel-letters/channel-norma-reed.jpg", alt: "Norma Reed channel letters" },
      { src: "/images/gallery/channel-letters/channel-avalee.jpg", alt: "Avalee channel letters" },
      { src: "/images/gallery/channel-letters/fiveguys.png", alt: "Five Guys illuminated channel letters" },
      { src: "/images/gallery/channel-letters/channel-9601.jpg", alt: "Channel letter installation" },
    ],
  },
  {
    slug: "storefront-signs",
    title: "Storefront Signs",
    shortDescription: "Complete storefront solutions including fascias, window lettering, and illuminated signs.",
    longDescription: "Your storefront is your first impression. A well-designed storefront sign package combines multiple sign types — illuminated channel letters or light boxes, window graphics, blade signs, and awnings — into a cohesive brand presence that attracts foot traffic and builds recognition. We work with business owners, landlords, and property managers across the GTA to design and install complete storefront signage packages.",
    image: "/images/services/storefront-signs.jpg",
    heroImage: "/images/heroes/storefront-golden-hour.jpg",
    features: ["Illuminated fascia signs", "Channel letter packages", "Window vinyl and graphics", "Projecting blade signs", "Under-awning signs", "Complete brand packages"],
    faq: [
      { question: "What types of storefront signs are available?", answer: "Common storefront sign types include illuminated channel letters, light box cabinets, dimensional letters, awning signs, blade/projecting signs, and window graphics. We often combine multiple types for maximum impact." },
      { question: "Can you match my existing brand guidelines?", answer: "Absolutely. We work from your brand guidelines, logo files, and color specifications to ensure your signage perfectly represents your brand." },
      { question: "Do you work with landlords on sign approvals?", answer: "Yes, we regularly coordinate with property managers and landlords on sign criteria, placement, and approvals as part of our project management service." },
    ],
    gallery: [
      { src: "/images/gallery/storefront-signs/storefront-main.png", alt: "Complete storefront signage package" },
      { src: "/images/gallery/storefront-signs/storefront-1.png", alt: "Storefront sign installation" },
      { src: "/images/gallery/storefront-signs/storefront-3.png", alt: "Illuminated storefront fascia" },
      { src: "/images/gallery/storefront-signs/storefront-4.png", alt: "Custom storefront branding" },
      { src: "/images/gallery/storefront-signs/storefront-5.png", alt: "Retail storefront signage" },
      { src: "/images/gallery/storefront-signs/storefront-booster-juice.jpg", alt: "Booster Juice storefront signs" },
      { src: "/images/gallery/storefront-signs/storefront-homecare.jpg", alt: "Homecare storefront signage" },
      { src: "/images/gallery/storefront-signs/storefront-smoke-bbq.jpg", alt: "Smoke BBQ restaurant signage" },
      { src: "/images/gallery/storefront-signs/storefront-vacation.jpg", alt: "Vacation travel agency storefront" },
      { src: "/images/gallery/storefront-signs/storefront-wicks-vape.jpg", alt: "Wicks Vape storefront signs" },
    ],
  },
  {
    slug: "vehicle-wraps",
    title: "Vehicle Wraps & Graphics",
    shortDescription: "Turn your vehicle into a mobile billboard with custom graphics and wraps.",
    longDescription: "Vehicle wraps are one of the most cost-effective forms of advertising, generating 30,000-70,000 daily impressions. Whether you need a full fleet wrap or a single delivery van, our vehicle graphics are printed on premium 3M and Avery vinyl with UV-protective lamination that lasts 5-7 years. We have wrapped vehicles for companies ranging from local contractors to national brands like UberEats.",
    image: "/images/services/vehicle-graphics.jpg",
    heroImage: "/images/heroes/vehicle-wrap-street.jpg",
    features: ["Full vehicle wraps", "Partial wraps and decals", "Fleet graphics programs", "Vinyl lettering", "Perforated window film", "Paint protection film"],
    faq: [
      { question: "How long does a vehicle wrap last?", answer: "A professionally installed vehicle wrap using premium 3M or Avery vinyl lasts 5-7 years with proper care." },
      { question: "Will a wrap damage my paint?", answer: "No. High-quality vinyl wraps actually protect your vehicle's paint. When removed professionally, your original paint will be in the same condition." },
      { question: "How long does installation take?", answer: "A full vehicle wrap typically takes 2-3 days for installation. Partial wraps and decals can often be completed in 1 day." },
    ],
    gallery: [
      { src: "/images/gallery/vehicle-wraps/vehicle-pullman.jpg", alt: "Pullman vehicle wrap" },
      { src: "/images/gallery/vehicle-wraps/vehicle-hongmall.jpg", alt: "Hongmall delivery van wrap" },
      { src: "/images/gallery/vehicle-wraps/vehicle-eco-compact.jpg", alt: "Eco Compact vehicle graphics" },
      { src: "/images/gallery/vehicle-wraps/vehicle-ecotech.jpg", alt: "Ecotech van wrap" },
      { src: "/images/gallery/vehicle-wraps/vehicle-humber.jpg", alt: "Humber College vehicle wrap" },
      { src: "/images/gallery/vehicle-wraps/vehicle-fix-easy.jpg", alt: "Fix Easy service vehicle wrap" },
      { src: "/images/gallery/vehicle-wraps/vehicle-flooring-canada.jpg", alt: "Flooring Canada fleet graphics" },
      { src: "/images/gallery/vehicle-wraps/vehicle-ice-cream.jpg", alt: "Ice cream truck wrap" },
      { src: "/images/gallery/vehicle-wraps/ubereats.jpg", alt: "UberEats delivery vehicle wrap" },
      { src: "/images/gallery/vehicle-wraps/vehicle-rosegold.jpg", alt: "Rosegold vehicle graphics" },
      { src: "/images/gallery/vehicle-wraps/dermameat.jpg", alt: "Dermameat vehicle wrap" },
    ],
  },
  {
    slug: "illuminated-signs",
    title: "Illuminated Signs",
    shortDescription: "Eye-catching illuminated signage for 24/7 brand visibility.",
    longDescription: "Illuminated signs ensure your business is visible around the clock. From channel letters and light boxes to LED message boards, we offer a full range of illuminated signage solutions. Our signs use energy-efficient LED technology that reduces operating costs while providing brilliant, even illumination.",
    image: "/images/services/light-boxes.jpg",
    heroImage: "/images/heroes/channel-letters-night.jpg",
    features: ["LED channel letters", "Light box cabinets", "Edge-lit signs", "Backlit panels", "LED message centers", "Neon-style LED flex"],
    faq: [
      { question: "What is more energy efficient — LED or neon?", answer: "LED signage uses 50-80% less energy than traditional neon, lasts significantly longer, and requires less maintenance." },
      { question: "Can illuminated signs be dimmed?", answer: "Yes. We can install dimmers or programmable controllers that adjust brightness based on time of day." },
      { question: "Do illuminated signs require special permits?", answer: "Most municipalities require permits for illuminated signage. We handle all permit research and applications." },
    ],
    gallery: [
      { src: "/images/gallery/light-boxes/lightbox-47815-fd6.jpg", alt: "Illuminated light box sign" },
      { src: "/images/gallery/light-boxes/lightbox-47815-76c.jpg", alt: "Backlit cabinet sign" },
      { src: "/images/gallery/light-boxes/lightbox-47815-a7f.jpg", alt: "Illuminated retail signage" },
      { src: "/images/gallery/light-boxes/lightbox-shopify-1.jpg", alt: "Double-sided light box" },
      { src: "/images/gallery/light-boxes/lightbox-shopify-2.jpg", alt: "Custom illuminated panel" },
    ],
  },
  {
    slug: "pylon-signs",
    title: "Pylon Signs",
    shortDescription: "High-visibility freestanding signs designed to grab attention from a distance.",
    longDescription: "Pylon signs are tall, freestanding structures that provide maximum visibility from roads and highways. They are essential for businesses set back from the road, multi-tenant commercial plazas, and locations that need to be seen from a distance. Our pylon signs are engineered to meet local building codes and wind load requirements.",
    image: "/images/services/pylon-signs.jpg",
    heroImage: "/images/heroes/pylon-road.jpg",
    features: ["Single-tenant pylons", "Multi-tenant directory pylons", "Illuminated panels", "Digital LED inserts", "Monument-style bases", "Permit coordination"],
    faq: [
      { question: "What is the difference between a pylon sign and a monument sign?", answer: "Pylon signs are elevated on poles for maximum height and road visibility. Monument signs sit at ground level with a solid base, offering a more architectural appearance." },
      { question: "How tall can a pylon sign be?", answer: "Height restrictions vary by municipality and zoning. In Vaughan, typical maximum heights range from 6m to 15m depending on the zone." },
      { question: "Can existing pylon signs be updated?", answer: "Yes. We frequently refurbish, re-face, or retrofit existing pylon structures with new panels, LED lighting, or digital displays." },
    ],
    gallery: [
      { src: "/images/gallery/pylon-signs/pylon-brock-road-refresh.jpg", alt: "Brock Road pylon sign" },
      { src: "/images/gallery/pylon-signs/pylon-img-2148.jpg", alt: "Multi-tenant pylon sign" },
      { src: "/images/gallery/pylon-signs/pylon-img-2712.jpg", alt: "Commercial pylon sign installation" },
      { src: "/images/gallery/pylon-signs/pylon-love-and-paws.jpg", alt: "Love and Paws pylon sign" },
      { src: "/images/gallery/pylon-signs/pylon-photo-2023.jpg", alt: "Illuminated pylon sign at night" },
      { src: "/images/gallery/pylon-signs/pylon-resized-2024.jpg", alt: "Freestanding pylon directory sign" },
      { src: "/images/gallery/pylon-signs/pylon-whatsapp-2025.jpg", alt: "Highway pylon sign" },
    ],
  },
  {
    slug: "indoor-signs",
    title: "Indoor Signs",
    shortDescription: "Professional interior branding solutions for reception areas, offices, and lobbies.",
    longDescription: "Interior signage shapes the experience of everyone who walks through your doors. From dimensional lobby logos to wayfinding systems, our indoor signage solutions help businesses project professionalism and reinforce brand identity. We work with brushed aluminum, acrylic, wood, PVC, and backlit panels.",
    image: "/images/services/indoor-signs.jpg",
    heroImage: "/images/heroes/office-lobby.jpg",
    features: ["Dimensional lobby signs", "Reception area branding", "Wayfinding and directory signs", "Acrylic and metal letters", "Wall murals and graphics", "ADA-compliant signage"],
    faq: [
      { question: "What materials are used for lobby signs?", answer: "Popular materials include brushed aluminum, stainless steel, acrylic, painted PVC, and real wood. The choice depends on your brand aesthetic and budget." },
      { question: "Can you install signs on any wall surface?", answer: "We install on drywall, concrete, brick, glass, and most other surfaces. Our team assesses your wall type during consultation." },
    ],
    gallery: [
      { src: "/images/gallery/indoor-signs/indoor-cml.jpg", alt: "CML lobby sign" },
      { src: "/images/gallery/indoor-signs/indoor-dael-thermal.jpg", alt: "Dael Thermal reception signage" },
      { src: "/images/gallery/indoor-signs/indoor-kiosoft.jpg", alt: "Kiosoft dimensional wall sign" },
      { src: "/images/gallery/indoor-signs/indoor-paulas-wig-boutique.jpg", alt: "Paula's Wig Boutique interior sign" },
      { src: "/images/gallery/indoor-signs/indoor-walking-on-a-cloud.jpg", alt: "Walking On A Cloud indoor sign" },
      { src: "/images/gallery/indoor-signs/indoor-sejj-jr.jpg", alt: "SEJJ JR indoor signage" },
      { src: "/images/gallery/indoor-signs/trubliss.jpg", alt: "TruBliss dimensional lobby sign" },
      { src: "/images/gallery/indoor-signs/innovatus.jpg", alt: "Innovatus reception sign" },
      { src: "/images/gallery/indoor-signs/indoor-3.png", alt: "Office wayfinding signage" },
      { src: "/images/gallery/indoor-signs/indoor-4.png", alt: "Interior branding display" },
    ],
  },
  {
    slug: "3d-signs-lettering",
    title: "3D Signs & Lettering",
    shortDescription: "Custom 3D illuminated and non-illuminated signs that provide depth and impact.",
    longDescription: "Three-dimensional signs and lettering add depth, shadow, and presence that flat signage simply cannot match. We fabricate 3D signage from aluminum, acrylic, PVC, stainless steel, and wood — and can produce letters from 2 inches to 6+ feet tall.",
    image: "/images/services/3d-signs.jpg",
    heroImage: "/images/services/3d-signs.jpg",
    features: ["Dimensional letters (painted or metallic)", "Illuminated 3D logos", "Foam letters with hard-coat finish", "Metal fabricated letters", "Acrylic formed letters", "Custom depths and finishes"],
    faq: [
      { question: "What materials can 3D letters be made from?", answer: "We fabricate 3D letters from aluminum, acrylic, PVC, stainless steel, bronze, and high-density foam with a hard-coat finish." },
      { question: "Can 3D letters be illuminated?", answer: "Yes. 3D letters can be front-lit, back-lit (halo effect), or edge-lit." },
    ],
    gallery: [
      { src: "/images/gallery/3d-signs-lettering/3d-boss-leather.jpg", alt: "Boss Leather 3D dimensional sign" },
      { src: "/images/gallery/3d-signs-lettering/3d-pain-specialists.jpg", alt: "Pain Specialists 3D lettering" },
      { src: "/images/gallery/3d-signs-lettering/3d-2016-photo.jpg", alt: "3D sign installation" },
      { src: "/images/gallery/3d-signs-lettering/3d-46856.jpg", alt: "Dimensional 3D letters" },
      { src: "/images/gallery/3d-signs-lettering/3d-5.png", alt: "3D logo signage" },
      { src: "/images/gallery/3d-signs-lettering/trimdepot.jpg", alt: "TrimDepot 3D dimensional sign" },
      { src: "/images/gallery/3d-signs-lettering/aquastar.jpg", alt: "AquaStar 3D lettering" },
      { src: "/images/gallery/3d-signs-lettering/elite.jpg", alt: "Elite 3D sign" },
    ],
  },
  {
    slug: "window-graphics",
    title: "Window Graphics",
    shortDescription: "Custom window decals and frostings for privacy and promotions.",
    longDescription: "Window graphics turn unused glass surfaces into valuable branding real estate. Whether you need frosted privacy film for a boardroom, vibrant promotional graphics for a retail storefront, or perforated vinyl that allows visibility from inside while displaying your brand outside, we have solutions for every application.",
    image: "/images/services/window-graphics.jpg",
    heroImage: "/images/services/window-graphics.jpg",
    features: ["Vinyl lettering and logos", "Frosted/etched film", "Perforated one-way vision", "Full window wraps", "Seasonal promotional graphics", "UV-protective films"],
    faq: [
      { question: "Can I see through window graphics from inside?", answer: "Yes. Perforated vinyl displays your graphics on the outside while allowing clear visibility from inside." },
      { question: "How long do window graphics last?", answer: "Interior window graphics can last 5+ years. Exterior graphics typically last 3-5 years depending on sun exposure." },
    ],
    gallery: [
      { src: "/images/gallery/window-graphics/window-20210519.jpg", alt: "Custom window graphics installation" },
      { src: "/images/gallery/window-graphics/window-di-paola.jpg", alt: "Di Paola window vinyl" },
      { src: "/images/gallery/window-graphics/window-divine.jpg", alt: "Divine window graphics" },
      { src: "/images/gallery/window-graphics/window-humber-college.jpg", alt: "Humber College window graphics" },
      { src: "/images/gallery/window-graphics/window-img-0307.jpg", alt: "Frosted window privacy film" },
      { src: "/images/gallery/window-graphics/window-img-0312.jpg", alt: "Custom window vinyl lettering" },
      { src: "/images/gallery/window-graphics/window-mary-browns.jpg", alt: "Mary Brown's storefront window graphics" },
      { src: "/images/gallery/window-graphics/window-spa.jpg", alt: "Spa window frosted film" },
      { src: "/images/gallery/window-graphics/happysmile.jpg", alt: "Happy Smile window graphics" },
    ],
  },
  {
    slug: "construction-signs",
    title: "Construction Signs",
    shortDescription: "Durable site signage for development, safety, and branding.",
    longDescription: "Construction and development signage serves dual purposes: meeting regulatory requirements and marketing your project to the community. From large-format hoarding graphics to site identification signs, directional signage, and safety postings, we provide complete construction signage solutions.",
    image: "/images/services/construction-signs.jpg",
    heroImage: "/images/services/construction-signs.jpg",
    features: ["Hoarding graphics", "Site identification signs", "Directional signage", "Safety and compliance signs", "Real estate development signs", "Temporary event signage"],
    faq: [
      { question: "What materials do you use for construction signs?", answer: "We use coroplast for temporary signs, aluminum composite panels for durable site ID signs, and heavy-duty vinyl on plywood for hoarding graphics." },
      { question: "How quickly can construction signs be produced?", answer: "Standard construction signs can be produced in 2-5 business days. Rush orders are available." },
    ],
    gallery: [
      { src: "/images/gallery/construction-signs/construction-1.png", alt: "Construction site signage" },
      { src: "/images/gallery/construction-signs/construction-2.png", alt: "Development hoarding graphics" },
      { src: "/images/gallery/construction-signs/construction-foresight.jpg", alt: "Foresight construction sign" },
      { src: "/images/gallery/construction-signs/construction-thumb.jpg", alt: "Construction site identification sign" },
    ],
  },
  {
    slug: "digital-signs",
    title: "Digital Signs",
    shortDescription: "Modern LED displays for dynamic messaging and high-impact advertising.",
    longDescription: "Digital signage allows you to update your messaging instantly, display dynamic content, and capture attention with bright, vivid LED displays. We supply, install, and configure digital signage systems with user-friendly content management software.",
    image: "/images/services/digital-signs.jpg",
    heroImage: "/images/services/digital-signs.jpg",
    features: ["Outdoor LED message centers", "Indoor digital displays", "Menu boards", "Video walls", "Content management systems", "Scheduling and automation"],
    faq: [
      { question: "How do I update the content on a digital sign?", answer: "Our digital signs come with cloud-based content management software. You can update from any computer or smartphone." },
      { question: "How bright are outdoor LED signs?", answer: "Our outdoor LED displays produce 5,000-8,000 nits of brightness, clearly visible even in direct sunlight." },
    ],
    gallery: [
      { src: "/images/gallery/digital-signs/digital-yonge-st.jpg", alt: "Yonge Street digital sign" },
      { src: "/images/gallery/digital-signs/digital-goldhawk.jpg", alt: "Goldhawk digital display" },
      { src: "/images/gallery/digital-signs/digital-full-color-p10.jpg", alt: "Full color P10 LED sign" },
      { src: "/images/gallery/digital-signs/digital-haviland-school.jpg", alt: "Haviland School digital sign" },
      { src: "/images/gallery/digital-signs/digital-sweetwater.jpg", alt: "Sweetwater digital signage" },
      { src: "/images/gallery/digital-signs/digital-crossings.jpg", alt: "Crossings LED message center" },
      { src: "/images/gallery/digital-signs/digital-1-ff8b.png", alt: "Digital sign installation" },
      { src: "/images/gallery/digital-signs/digital-img-3762.jpg", alt: "Outdoor LED display" },
      { src: "/images/gallery/digital-signs/digital-walkerpoints.jpg", alt: "Walkerpoints digital sign" },
    ],
  },
  {
    slug: "awning-graphics",
    title: "Awning Graphics",
    shortDescription: "Stylish and functional awnings to enhance your storefront and provide shade.",
    longDescription: "Awnings combine form and function — they protect customers from weather, reduce glare and heat gain, and provide valuable branding space. We offer custom-printed fabric awnings, backlit awning signs, and rigid metal awning structures.",
    image: "/images/services/awning-graphics.jpg",
    heroImage: "/images/services/awning-graphics.jpg",
    features: ["Printed fabric awnings", "Backlit awning signs", "Rigid metal canopies", "Retractable awnings", "Custom shapes and sizes", "Weather-resistant materials"],
    faq: [
      { question: "How long do awning graphics last?", answer: "Premium awning fabrics with UV-resistant inks typically last 5-8 years before needing replacement." },
      { question: "Can awnings be illuminated?", answer: "Yes. Backlit awnings use internal lighting to illuminate your graphics at night." },
    ],
    gallery: [
      { src: "/images/gallery/awning-graphics/awning-1.jpg", alt: "Custom awning signage" },
      { src: "/images/gallery/awning-graphics/awning-2.jpg", alt: "Printed fabric awning" },
      { src: "/images/gallery/awning-graphics/awning-5.png", alt: "Backlit awning sign" },
      { src: "/images/gallery/awning-graphics/awning-7.png", alt: "Retail awning graphics" },
      { src: "/images/gallery/awning-graphics/awning-boss-leather.jpg", alt: "Boss Leather awning" },
      { src: "/images/gallery/awning-graphics/awning-harps.jpg", alt: "Harps awning signage" },
      { src: "/images/gallery/awning-graphics/awning-img-0334.jpg", alt: "Custom awning installation" },
    ],
  },
  {
    slug: "led-backlit-signs",
    title: "LED Backlit Signs",
    shortDescription: "High-impact illuminated signs with a sophisticated halo effect.",
    longDescription: "LED backlit signs project light behind the letters onto the mounting surface, creating a distinctive glow effect. This technique produces an upscale, architectural look popular with hotels, medical offices, law firms, and premium retail brands.",
    image: "/images/services/led-backlit.jpg",
    heroImage: "/images/services/led-backlit.jpg",
    features: ["Halo-lit channel letters", "Backlit dimensional logos", "Edge-lit acrylic panels", "Brushed metal with LED backglow", "Custom color temperatures", "Indoor and outdoor options"],
    faq: [
      { question: "What is the difference between backlit and front-lit signs?", answer: "Front-lit signs illuminate the face directly. Backlit signs project light behind the letter onto the wall, creating a softer, more sophisticated glow." },
      { question: "Can backlit signs be used indoors?", answer: "Absolutely. Backlit lobby signs and reception logos are among our most popular interior signage products." },
    ],
    gallery: [
      { src: "/images/gallery/led-backlit-signs/led-32897.jpg", alt: "LED backlit channel letters" },
      { src: "/images/gallery/led-backlit-signs/led-32897-2.jpg", alt: "Halo-lit sign installation" },
      { src: "/images/gallery/led-backlit-signs/led-46925.jpg", alt: "Backlit dimensional logo" },
      { src: "/images/gallery/led-backlit-signs/led-47052.jpg", alt: "LED backglow letters" },
      { src: "/images/gallery/led-backlit-signs/led-47052-2.jpg", alt: "Edge-lit acrylic sign" },
      { src: "/images/gallery/led-backlit-signs/led-47789.jpg", alt: "Brushed metal backlit sign" },
    ],
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}
